openapi: 3.0.0
info:
  title: HMIS Developer Service
  version: 1.0.1
  contact:
    name: API Source
    email: support@hslynk.com
    url: https://github.com/hmis-api/developer-service-api
  # Name of the license and a URL to the license description.
  license:
    name: Open Source License
    url: https://github.com/hmis-api/developer-service-api/blob/master/LICENSE
servers:
  - url: 'https://api.hslynk.com/hmis-developer-service/rest'
paths:
  /developercompanies:
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  developerCompanies:
                    paginationResult:
                      startIndex: '0'
                      itemsReturned: '2'
                      totalItems: '16'
                    developerCompanies:
                      developerCompany:
                        - developerCompanyId: AA8F9FD9-532D-4D59-B397-5D94CEC6A868
                          name: Amazing Inc.
                          domain: www.hmis.com
                          owner:
                            username: username@gmail.com
                            firstName: firstname
                            lastName: lastname
                        - developerCompanyId: 5D94CEC6A868-532D-4D59-B397-AA8F9FD9
                          name: HMIS.
                          domain: www.hmis.com
                          owner:
                            username: username@gmail.com
                            firstName: firstname
                            lastName: lastname
        '401':
          description: ''
          content:
            application/json:
              schema:
                example:
                  errors:
                    error:
                      code: INVALID_SESSION_TOKEN
                      message: >-
                        The specified session/access token is not valid or has
                        expired.
      description: >
        Gets ( reads or retrieves) all developer companies.It filters the result
        based on the request parameters (optional) 'trustedApp.status' or
        'service.status'. The user must have "DCS_GET_ALL_DEVELOPER_COMPANY"
        permission to use this API.
      operationId: GET_developercompanies
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
  '/developercompanies/{developercompanyid}/approvaldecision':
    post:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                    developerCompanyStatus: {}
        '403':
          description: ''
          content:
            application/json:
              schema:
                example:
                  errors:
                    error:
                      code: ILLEGAL_STATE
                      message: >-
                        The developer company can not be approved or rejected
                        because its current status is not SUBMITTED.
        '404':
          description: ''
          content:
            application/json:
              schema:
                example:
                  errors:
                    error:
                      code: DEVELOPER_COMPANY_NOT_FOUND
                      message: >-
                        A developer company with the specified
                        developerCompanyId is not found.
      description: >
        It approves or rejects a developer company. If the developer company is
        approved the status of the developer company is changed to ACTIVE and if
        the developer company is rejected the status of the developer company is
        changed to REJECTED. An email is sent to the owner of the developer
        company with the approval decision.

        A developer company can be approved or rejected only if its current
        status is SUBMITTED.
        status attribute accepted values are ACTIVE and REJECTED
      operationId: POST_developercompanies-developercompanyid-approvaldecision
      requestBody:
        content:
          application/json:
            example:
              developerCompanyStatus:
                status: ACTIVE
                comment: service has been approved
            schema:
              type: string
        required: true
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    parameters:
      - name: developercompanyid
        in: path
        required: true
        schema:
          type: string
  '/developercompanies/{developercompanyid}/accounts':
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  developerCompanyAccounts:
                    pagination:
                      from: 0
                      returned: 2
                      total: 2
                      maximum: 30
                      sort: {}
                    developerCompanyAccount:
                      - account:
                          accountId: 22095B4D-2C97-4BF2-AF61-ACEFB4904535
                          username: SuryaYadavallitest1@gmail.com
                          firstName: Surya
                          lastName: Yadavalli
                          middleName: P
                        role: ADMIN
                        owner: 'true'
                      - account:
                          accountId: 46B0C97E-E8AB-4259-A299-16A3B974D6F0
                          username: surya.yadavalli@gmail.com
                          firstName: Surya
                          lastName: Yadavalli
                          middleName: L
                          alias: Surya K
                        role: BASIC
                        owner: 'false'
        '403':
          description: ''
          content:
            application/json:
              schema:
                example:
                  errors:
                    error:
                      code: INVALID_SESSION_TOKEN
                      message: >-
                        The specified session/access token is not valid or has
                        expired.
      description: >
        Gets (aka reads or retrieves) all accounts associated with the specified
        developer company. Only the accounts associated with a developer company
        in "ADMIN" role can perform this operation for that developer company.
      operationId: GET_developercompanies-developercompanyid-accounts
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
        - name : developercompanyid
          required : true
          in: path
          schema:
            type: string
        - name: startIndex
          in: query
          schema:
            default: '0'
            type: string
        - name: maxItems
          in: query
          schema:
            default: '30'
            type: string
  '/developercompanies/{developercompanyid}/services':
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  services:
                    pagination:
                      from: 0
                      returned: 2
                      total: 2
                      maximum: 30
                      sort: {}
                    service:
                      - serviceId: 22095B4D-2C97-4BF2-AF61-ACEFB4904535
                        friendlyName: HMIS API  service
                        description: HMIS API service description
                        licenseType: NONE
                        status: IN_DEVELOPMENT
                      - serviceId: ACEFB4904535-2C97-4BF2-AF61-22095B4D
                        friendlyName: I am a sample service
                        description: I am a sample service description
                        status: ACTIVE
        '403':
          description: ''
          content:
            application/json:
              schema:
                example:
                  errors:
                    error:
                      code: INVALID_SESSION_TOKEN
                      message: >-
                        The specified session/access token is not valid or has
                        expired.
      description: >
        Gets (aka reads or retrieves) all services associated with the specified
        developer company. Only the accounts associated with a developer company
        in "ADMIN" role or any user with permission of "READ_ANY_SERVICE" can
        perform this operation for that developer company.
      operationId: GET_developercompanies-developercompanyid-services
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
        - name : developercompanyid
          required : true
          in: path
          schema:
            type: string
        - name: startIndex
          in: query
          schema:
            default: '0'
            type: string
        - name: maxItems
          in: query
          schema:
            default: '30'
            type: string
  '/developercompanies/{serviceid}':
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  service:
                    serviceId: 22095B4D-2C97-4BF2-AF61-ACEFB4904535
                    friendlyName: sample service
                    description: sample service description
                    status: IN_DEVELOPMENT
        '404':
          description: ''
          content:
            application/json:
              schema:
                example:
                  errors:
                    error:
                      code: SERVICE_NOT_FOUND
                      message: A service with the specified serviceId is not found.
      description: >-
        Gets (aka reads or retrieves) a specific service. Only the accounts
        associated with a developer company in "ADMIN" role can perform this
        operation for that developer company.
      operationId: GET_developercompanies-serviceid
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
        - name : serviceid
          required : true
          in: path
          schema:
            type: string
  '/services/{serviceid}/approvaldecision':
    post:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  serviceStatus:
                    status: ACTIVE
                    comment: service has been approved
        '403':
          description: ''
          content:
            application/json:
              schema:
                example:
                  errors:
                    error:
                      code: ILLEGAL_STATE
                      message: >-
                        The service can not be updated because its status is not
                        SUBMITTED.
        '404':
          description: ''
          content:
            application/json:
              schema:
                example:
                  errors:
                    error:
                      code: SERVICE_NOT_FOUND
                      message: A service with the specified serviceId is not found.
      description: >
        It approves or rejects a service. If the service is approved the status
        of the service is changed to ACTIVE and if the service is rejected the
        status of the service is changed to IN_DEVELOPMENT. An email is sent to
        the owner of the developer company with the approval decision.

        A service can be approved or rejected only if its current status is
        SUBMITTED.
        status attribute allowed values are ACTIVE and REJECTED
      operationId: POST_services-serviceid-approvaldecision
      requestBody:
        content:
          application/json:
            example:
              serviceStatus:
                status: ACTIVE
                comment: service has been approved
            schema:
              type: string
        required: true
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    parameters:
      - name: serviceid
        in: path
        required: true
        schema:
          type: string
  '/services/{serviceid}/trustedapps':
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  trustedApps:
                    pagination:
                      from: 0
                      returned: 2
                      total: 2
                      maximum: 30
                      sort: {}
                    trustedApp:
                      - trustedAppId: 22095B4D-2C97-4BF2-AF61-ACEFB4904535
                        friendlyName: Sample Trusted app1
                        description: Sample Trusted app1 description
                        trustedAppSecret: ajkdjledkaelanmcxsnjekldkleldfasfsd
                        logoUrl: 'http://logos/logo1.png'
                        trustedAppProfileType: NATIVE
                        trustedAppFamilyType: APP
                        refreshTokenSupported: 'true'
                        implicitGrantSupported: 'false'
                        authCodeGrantSupported: 'true'
                        status: ACTIVE
                      - trustedAppId: ACEFB4904535-2C97-4BF2-AF61-22095B4D
                        friendlyName: Sample Trusted app2
                        description: Sample Trusted app2 description
                        trustedAppSecret: ghgskhgklgwggwewfsjdfasf
                        logoUrl: 'http://logos/logo1.png'
                        trustedAppProfileType: NATIVE
                        trustedAppFamilyType: APP
                        refreshTokenSupported: 'true'
                        implicitGrantSupported: 'false'
                        authCodeGrantSupported: 'true'
                        status: IN_DEVELOPMENT
        '404':
          description: ''
          content:
            application/json:
              schema:
                example:
                  errors:
                    error:
                      code: SERVICE_NOT_FOUND
                      message: A service with the specified serviceId is not found.
      description: >-
        Gets (aka reads or retrieves) all trustedApps associated with the
        specified service. Only the accounts associated with a developer company
        in "ADMIN" role or any user with permission of "READ_ANY_CLIENT" can
        perform this operation for that developer company.
      operationId: GET_services-serviceid-trustedapps
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
        - name: startIndex
          in: query
          schema:
            default: '0'
            type: string
        - name: maxItems
          in: query
          schema:
            default: '30'
            type: string
        - name : serviceid
          required : true
          in: path
          schema:
            type: string
  '/services/{trustedappid}':
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  trustedApp:
                    trustedAppTypeId: 631D1191-9AC5-4F3F-836A-8DB0DBAE3CD3
                    friendlyname: Friendly Name_1437006937244
                    description: Description
                    status: IN_DEVELOPMENT
                    trustedAppSecret: 7432e99debbe4fd1af0ea6eb65b4f3e4
        '404':
          description: ''
          content:
            application/json:
              schema:
                example:
                  errors:
                    error:
                      code: CLIENT_NOT_FOUND
                      message: >-
                        A trustedApp with the specified trustedAppId is not
                        found.
      description: >
        Gets (aka reads or retrieves) a specific trustedApp. Only the accounts
        associated with a developer company in "ADMIN" role can perform this
        operation for that developer company.
      operationId: GET_services-trustedappid
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
        - name : trustedappid
          required : true
          in: path
          schema:
            type: string
  '/services/{trustedappid}/trustedappsecret':
    put:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  trustedApp:
                    trustedAppId: 22095B4D-2C97-4BF2-AF61-ACEFB4904535
                    trustedAppSecret: ajkdjledkaelanmcxsnjekldkleldfasfsd
        '404':
          description: ''
          content:
            application/json:
              schema:
                example:
                  errors:
                    error:
                      code: CLIENT_NOT_FOUND
                      message: >-
                        A trustedApp with the specified trustedAppId is not
                        found.
      description: >
        It generates a new trustedApp secret for the the specified trustedApp.
        Only the accounts associated with a developer company in "ADMIN" role
        can perform this operation for that developer company.
      operationId: PUT_services-trustedappid-trustedappsecret
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    parameters:
      - name: trustedappid
        in: path
        required: true
        schema:
          type: string

  '/services/{trustedappid}/approvaldecision':
    post:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  trustedAppStatus:
                    status: ACTIVE
                    comment: trustedApp has been approved.
        '403':
          description: ''
          content:
            application/json:
              schema:
                example:
                  errors:
                    error:
                      code: ILLEGAL_STATE
                      message: >-
                        The trustedApp can not be approved because its current
                        status is not SUBMITTED.
        '404':
          description: ''
          content:
            application/json:
              schema:
                example:
                  errors:
                    error:
                      code: CLIENT_NOT_FOUND
                      message: >-
                        A trustedApp with the specified trustedAppId is not
                        found.
      description: >
        It approves or rejects a trustedApp. If the trustedApp is approved the
        status of the trustedApp is changed to ACTIVE and if the trustedApp is
        rejected the status of the trustedApp is changed to IN_DEVELOPMENT. An
        email is sent to the owner of the developer company with the approval
        decision. User must have "MODIFY_ANY_TRUSTEDAPP_APPROVAL" permission to
        use this API. See user-level authroization permissions

        A trustedApp can be approved or rejected only if its current status is
        SUBMITTED.
      operationId: POST_services-trustedappid-approvaldecision
      requestBody:
        content:
          application/json:
            example:
              trustedAppStatus:
                status: ACTIVE
                comment: trustedApp has been approved.
            schema:
              type: string
        required: true
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    parameters:
      - name: trustedappid
        in: path
        required: true
        schema:
          type: string
components:
  schemas: {}
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes:
    oauth_2_0:
      description: |
        The HMIS API supports OAuth 2.0 for authenticating all API requests.
      type: oauth2
      flows:
        password:
          tokenUrl: 'https://hslynk.com/hmis-authorization-service/rest/token'
          scopes:
            user: ''
            administrator: ''
  links: {}
  callbacks: {}
